export default {
  '/': 'Главная',
  '/employees': 'Сотрудники',
  '/suppliers': 'Поставщики',
  '/warehouses': 'Склады',
  '/goods-receipts': 'Приход товара',
  '/goods-receipts/create': 'Добавить накладную прихода',
  '/goods-receipts/*/edit': 'Редактировать накладную прихода',
  '/categories': 'Категории товара',
  '/category-groups': 'Группы категорий товара',
  '/products': 'Справочник товаров',
  '/products/create': 'Добавить новую модель',
  '/products/*/edit': 'Редактировать модель',
  '/inventory-adjustments': 'Инвентаризация',
  '/inventory-transfers': 'Перемещение товара',
  '/points-of-sale': 'Точки продаж',
  '/points-of-sale/*/shifts': 'Смены на точке продаж',
  '/customers': 'Клиенты',
  '/product-variants': 'Список товаров',
  '/settings': 'Настройки'
}
